# Wave 1 - the ClusterIssuers, which are cert-manager CRDs from wave 0.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default

  source:
    repoURL: https://github.com/manish-jha18/devboard.git
    targetRevision: mega-project
    path: gitops/cert-manager

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
