apiVersion: v1
kind: Service
metadata:
  name: {{ include "devboard.fullname" . }}
  labels:
    {{- include "devboard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "devboard.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
